config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  

  # todos routes 
  get '/todos', action: :index, controller: 'todos'
  get 'todos/new', action: :new, controller: 'todos'
  post '/todos/new', action: :create_todo, controller: 'todos'
  get '/todos/:id/edit', action: :edit_todo, controller: 'todos'
  patch '/todos/:id/edit', action: :update_todo, controller: 'todos'
  delete '/todos/:id', action: :destroy, controller: 'todos'
  patch '/todos/:id/mark', action: :mark_completed, controller: 'todos'

  # Comment routes 
  get '/todos/:id', action: :show, controller: 'comments'
  post '/todos/:id/comment', action: :add_comment, controller: 'comments'
  
  # user routes 
  get '/signup', action: :new, controller: 'users'
  post '/signup', action: :create_user, controller: 'users'
  get '/users/:id/edit', action: :edit_user, controller: 'users'
  patch '/users/:id/edit', action: :update_user_details, controller: 'users'
  get '/users/:id', action: :show_user_details, controller: 'users'
  get '/users', action: :all_users, controller: 'users'
  delete '/users/:id', action: :destroy, controller: 'users'



  get '/login', action: :new, controller: 'sessions'
  post '/login', action: :create, controller: 'sessions'
  delete '/logout', action: :destroy, controller: 'sessions'


  
  get ':not_found', action: :invalid_url, controller: 'application'


end

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag 'navbar' %>
<header class="todo_nav">
    <div class="todos_logo" id="todo_logo">
        <%= link_to "Todo List", root_path , class: "nav_link" %>
    </div>
    <ul class="nav_link_list">
        <% if logged_in? %>
            <li> <%= link_to "#{@current_user[:username]}", "/users/#{@current_user[:id]}" , class: "nav_link" %> </li>
            <li> <%= link_to "Users", users_path , class: "nav_link" %> </li>
            <li> <%= link_to "Create new todo", todos_new_path , class: "nav_link" %> </li>
            <li> <%= link_to "Logout", "/logout" , class: "nav_link", method: :delete %> </li>
        <% end %>
    </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> | Todos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <% flash.each do |key,value|%>
      <p class='flash_message'> <%= value %> </p>
    <% end %>
    <%= yield %>
    <br><br>
    <% if false %>
      <%= debug(params) if Rails.env.development? %>
    <% end %>
    
  </body>
</html>